[IRT-1329] refactor: Improve error messages' clarity
Web3Auth/mpc-core-kit pull request #121
Opened 2024-04-30 09:29 UTC by huggingbot

### Description
- Improve error messages' clarity
- Remove duplicate error checks

2024-05-02 14:39 UTC, himanshuchawla009 requested changes

2024-05-02 14:39 UTC, himanshuchawla009 commented on package.json
> +    "ts-custom-error": "^3.3.1"
can we just copy the required files from this lib, rather thn downloading. I checked we just need 1 class and 2 utility functions from this lib.

2024-05-03 09:20 UTC, ieow commented
@huggingbot  Can you rebase this PR to v3

2024-05-07 05:04 UTC, himanshuchawla009 approved these changes
lgtm

2024-05-07 05:05 UTC, merged