feat: remove provider
Web3Auth/mpc-core-kit pull request #135
Opened 2024-05-03 09:04 UTC by ieow

remove provider
#123

2024-05-06 07:46 UTC, matthiasgeihs reviewed
Remove `public async setupProvider`?

Remove dependencies?
- @web3auth-mpc/ethereum-provider
- @web3auth/base-provider
- @metamask/swappable-obj-proxy

2024-05-06 07:46 UTC, matthiasgeihs commented on tests/login.spec.ts
> +      // assert.strictEqual(result, DEFAULT_CHAIN_CONFIG.chainId);
wanna remove these later?

2024-05-06 07:46 UTC, matthiasgeihs commented on tests/login.spec.ts
> +      // assert.strictEqual(result, DEFAULT_CHAIN_CONFIG.chainId);
remove?

2024-05-07 05:02 UTC, himanshuchawla009 requested changes

2024-05-07 05:05 UTC, ieow commented on src/mpcCoreKit.ts
> -    if (recoveryParam < 27) {
yes.
for pcs , they add another check to revert the modified value

2024-05-09 07:27 UTC, himanshuchawla009 commented on src/mpcCoreKit.ts
> -    if (recoveryParam < 27) {
got it, will ask devrels to validate and write a example around it using viem

2024-05-09 07:28 UTC, himanshuchawla009 approved these changes

2024-05-09 07:28 UTC, himanshuchawla009 commented
need to resolve merge conflicts

2024-05-14 08:56 UTC, matthiasgeihs commented on demo/redirect-flow-example/src/App.tsx
> +    // or
Let's try to remove all commented out code before merging. Doesn't look good in production code...

2024-05-14 08:56 UTC, matthiasgeihs commented on demo/redirect-flow-example/src/App.tsx
> +    // })
Let's try to remove all commented out code before merging. Doesn't look good in production code...

2024-05-14 08:56 UTC, matthiasgeihs commented on demo/redirect-flow-example/src/App.tsx
> +    // })
Let's try to remove all commented out code before merging. Doesn't look good in production code...

2024-05-16 01:42 UTC, matthiasgeihs commented
something that i wondered just now:
the demos heavily rely on usage of the provider, right? how do you deal with this? @ieow do you simply remove all of the respective functionality from the demos?

2024-05-17 08:36 UTC, himanshuchawla009 approved these changes
lgtm

2024-05-17 08:36 UTC, merged