feat: optional session manager
Web3Auth/mpc-core-kit pull request #175
Opened 2024-09-23 04:43 UTC by ieow

## Motivation and Context

Jira Link:
\optional session manager
- undefined / disabled when sessionTime is 0

## Description

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project. (run lint)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-01 05:22 UTC, himanshuchawla009 requested changes

2024-11-01 05:22 UTC, himanshuchawla009 commented on src/mpcCoreKit.ts
> +    if (this.options.sessionTime !== 0) {
in constructor sessionTime is being set to 86400 if nothing or 0 is passed, so i think this wont work until we handle that

2024-11-04 15:52 UTC, himanshuchawla009 requested changes

2024-11-04 15:52 UTC, himanshuchawla009 commented on src/mpcCoreKit.ts
> +    if (options.enableSessionManager === undefined) options.enableSessionManager = true;
i think changing name to `disableSessionManager` makes more sense, since its enabled by default.

2024-11-05 04:14 UTC, himanshuchawla009 approved these changes

2024-11-05 04:38 UTC, himanshuchawla009 approved these changes

2024-11-05 04:55 UTC, ieow commented
close in favor pr #188

2024-11-05 04:55 UTC, closed without merging